jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'macosx') }}:
      vmImage: macOS 10.13
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: Ubuntu 16.04
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: vs2017-win2016
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:

  - ${{ if eq(parameters.os, 'linux') }}:
    - script: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
      displayName: Setting up Xvfb

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install tox
    displayName: Installing tox

  - script: tox -e test
    displayName: Running tests
    env:
      DISPLAY: :99.0

  - script: |
        pip install codecov
        codecov --name ${{ format(parameters.name) }}
    displayName: Reporting coverage results to codecov
    env:
      CODECOV_TOKEN: $(codecov.token)
